title: The Trippy Frog | Himalayan Recreational Club
email: thetrippyfrog@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  The Trippy Frog is a company that deals with outdoor adventurous activities full of tremendous fun, thrill and for sure give you an adrenaline rush. A Himalayan recreational club that deals with outdoor adventurous sports like rafting, paragliding, trekking etc.
baseurl: ''
url: https://trippyfrog.com

permalink: slug

collections:
    activities:
        output: true
        permalink: /:title
        include: app-assets

defaults:
  - scope:
      path: ''
      type: 'activities'
    values:
      layout: 'default'
      image: true
      type: 'activities'

exclude:
  - Gemfile
  - Gemfile.lock
  - readme.md
  - license
  - CNAME
plugins:
  - jekyll-sitemap
strict_front_matter: true
